#ifndef ENUMS_HPP
#define ENUMS_HPP

enum TokenType {
  TOKEN_UNKNOWN,
  TOKEN_LISTEN,
  TOKEN_SERVER_NAME,
  TOKEN_MAX_BODY,
  TOKEN_ERROR_PAGE,
  TOKEN_LOCATION,
  // Location directives
  TOKEN_ALLOW_METHODS,
  TOKEN_ROOT,
  TOKEN_AUTOINDEX,
  TOKEN_INDEX,
  TOKEN_EXTENSION,
  TOKEN_UPLOAD_PATH,
  TOKEN_REDIRECT,
  TOKEN_CGI_PATH
};

enum HttpStatus {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  TEMPORARY_REDIRECT = 307,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  LENGTH_REQUIRED = 411,
  URI_TOO_LONG = 414,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502
};

enum RequestMethod { NONE, GET, HEAD, POST, DELETE, UNKNOWN_METHOD };

#endif
